[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[rpc_endpoints]
base_sepolia = "${RPC_URL}"
base = "${RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
